config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :telefones
  resources :enderecos
  resources :proponentes do
    member do
      patch :atualizar_salario
    end
    collection do
      get :relatorio
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/endereco.rb
# frozen_string_literal: true

# app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :proponente

  validates :logradouro, :numero, :bairro, :cidade, :estado, :cep, presence: true
end

app/models/proponente.rb
# frozen_string_literal: true

# app/models/proponente.rb
class Proponente < ApplicationRecord
  has_one :endereco, dependent: :destroy
  has_many :telefones, dependent: :destroy
  accepts_nested_attributes_for :endereco, :telefones

  before_save :calcular_inss

  private

  def calcular_inss
    self.inss = calcular_desconto_inss(self.salario)
  end

  def calcular_desconto_inss(salario)
    if salario <= 1045.00
      salario * 0.075
    elsif salario <= 2089.60
      (1045.00 * 0.075) + ((salario - 1045.00) * 0.09)
    elsif salario <= 3134.40
      (1045.00 * 0.075) + (1044.60 * 0.09) + ((salario - 2089.60) * 0.12)
    elsif salario <= 6101.06
      (1045.00 * 0.075) + (1044.60 * 0.09) + (1044.80 * 0.12) + ((salario - 3134.40) * 0.14)
    else
      713.08
    end
  end
end

app/models/telefone.rb
# frozen_string_literal: true

# app/models/telefone.rb
class Telefone < ApplicationRecord
  belongs_to :proponente

  enum tipo: { pessoal: 'pessoal', referencia: 'referencia' }

  validates :numero, :tipo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: %i[ show edit update destroy ]

  # GET /enderecos or /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1 or /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos or /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully created." }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1 or /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully updated." }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1 or /enderecos/1.json
  def destroy
    @endereco.destroy!

    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: "Endereco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def endereco_params
      params.require(:endereco).permit(:logradouro, :numero, :bairro, :cidade, :estado, :cep, :proponente_id)
    end
end

app/controllers/proponentes_controller.rb
# frozen_string_literal: true

class ProponentesController < ApplicationController
  before_action :set_proponente, only: %i[ show edit update destroy ]

  def index
    @proponentes = Proponente.page(params[:page]).per(5)
  end

  def show
    @proponente = Proponente.find(params[:id])
  end

  def new
    @proponente = Proponente.new
    @proponente.build_endereco
    @proponente.telefones.build
  end

  def create
    @proponente = Proponente.new(proponente_params)
    if @proponente.save
      redirect_to @proponente, notice: 'Proponente was successfully created.'
    else
      render :new
    end
  end

  def edit
    @proponente = Proponente.find(params[:id])
  end

  def update
    @proponente = Proponente.find(params[:id])
    if @proponente.update(proponente_params)
      redirect_to @proponente, notice: 'Proponente was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @proponente = Proponente.find(params[:id])
    @proponente.destroy
    redirect_to proponentes_url, notice: 'Proponente was successfully destroyed.'
  end

  def calcular_inss
    salario = params[:salario].to_f
    inss = Proponente.new.calcular_desconto_inss(salario)
    render json: { inss: inss }
  end

  def relatorio
    @proponentes = Proponente.all.group_by do |proponente|
      case proponente.salario
      when 0..1045.00 then 'Até R$ 1.045,00'
      when 1045.01..2089.60 then 'De R$ 1.045,01 a R$ 2.089,60'
      when 2089.61..3134.40 then 'De R$ 2.089,61 até R$ 3.134,40'
      else 'De R$ 3.134,41 até R$ 6.101,06'
      end
    end
  end

  def atualizar_salario
    proponente = Proponente.find(params[:id])
    novo_salario = params[:salario].to_f
    UpdateSalarioJob.perform_later(proponente.id, novo_salario)
    redirect_to proponente, notice: 'Salário atualizado com sucesso.'
  end

  private

  def set_proponente
    @proponente = Proponente.find(params[:id])
  end

  def proponente_params
    params.require(:proponente).permit(:nome, :cpf, :data_de_nascimento, :salario, endereco_attributes: [:logradouro, :numero, :bairro, :cidade, :estado, :cep], telefones_attributes: [:numero, :tipo])
  end
end

app/controllers/telefones_controller.rb
class TelefonesController < ApplicationController
  before_action :set_telefone, only: %i[ show edit update destroy ]

  # GET /telefones or /telefones.json
  def index
    @telefones = Telefone.all
  end

  # GET /telefones/1 or /telefones/1.json
  def show
  end

  # GET /telefones/new
  def new
    @telefone = Telefone.new
  end

  # GET /telefones/1/edit
  def edit
  end

  # POST /telefones or /telefones.json
  def create
    @telefone = Telefone.new(telefone_params)

    respond_to do |format|
      if @telefone.save
        format.html { redirect_to telefone_url(@telefone), notice: "Telefone was successfully created." }
        format.json { render :show, status: :created, location: @telefone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telefones/1 or /telefones/1.json
  def update
    respond_to do |format|
      if @telefone.update(telefone_params)
        format.html { redirect_to telefone_url(@telefone), notice: "Telefone was successfully updated." }
        format.json { render :show, status: :ok, location: @telefone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telefones/1 or /telefones/1.json
  def destroy
    @telefone.destroy!

    respond_to do |format|
      format.html { redirect_to telefones_url, notice: "Telefone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telefone
      @telefone = Telefone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def telefone_params
      params.require(:telefone).permit(:numero, :tipo, :proponente_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/proponentes_helper.rb
module ProponentesHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/views/enderecos/_endereco.html.erb
<div id="<%= dom_id endereco %>">
  <p>
    <strong>Logradouro:</strong>
    <%= endereco.logradouro %>
  </p>

  <p>
    <strong>Numero:</strong>
    <%= endereco.numero %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= endereco.bairro %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= endereco.cidade %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= endereco.estado %>
  </p>

  <p>
    <strong>Cep:</strong>
    <%= endereco.cep %>
  </p>

  <p>
    <strong>Proponente:</strong>
    <%= endereco.proponente_id %>
  </p>

</div>

app/views/enderecos/_form.html.erb
<%= form_with(model: endereco) do |form| %>
  <% if endereco.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
        <% endereco.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :logradouro, style: "display: block" %>
    <%= form.text_field :logradouro %>
  </div>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.text_field :numero %>
  </div>

  <div>
    <%= form.label :bairro, style: "display: block" %>
    <%= form.text_field :bairro %>
  </div>

  <div>
    <%= form.label :cidade, style: "display: block" %>
    <%= form.text_field :cidade %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.text_field :estado %>
  </div>

  <div>
    <%= form.label :cep, style: "display: block" %>
    <%= form.text_field :cep %>
  </div>

  <div>
    <%= form.label :proponente_id, style: "display: block" %>
    <%= form.text_field :proponente_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing endereco</h1>

<%= render "form", endereco: @endereco %>

<br>

<div>
  <%= link_to "Show this endereco", @endereco %> |
  <%= link_to "Back to enderecos", enderecos_path %>
</div>

app/views/enderecos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enderecos</h1>

<div id="enderecos">
  <% @enderecos.each do |endereco| %>
    <%= render endereco %>
    <p>
      <%= link_to "Show this endereco", endereco %>
    </p>
  <% end %>
</div>

<%= link_to "New endereco", new_endereco_path %>

app/views/enderecos/new.html.erb
<h1>New endereco</h1>

<%= render "form", endereco: @endereco %>

<br>

<div>
  <%= link_to "Back to enderecos", enderecos_path %>
</div>

app/views/enderecos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @endereco %>

<div>
  <%= link_to "Edit this endereco", edit_endereco_path(@endereco) %> |
  <%= link_to "Back to enderecos", enderecos_path %>

  <%= button_to "Destroy this endereco", @endereco, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DescontoInss</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">DescontoInss</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card-body">
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/proponentes/_form.html.erb
<%= form_with(model: proponente, local: false) do |form| %>
  <div class="row">
    <div class="col-md-6 mb-3">
      <%= form.label :nome, class: "form-label" %>
      <%= form.text_field :nome, class: "form-control" %>
    </div>
    <div class="col-md-6 mb-3">
      <%= form.label :cpf, class: "form-label" %>
      <%= form.text_field :cpf, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mb-3">
      <%= form.label :data_de_nascimento, class: "form-label" %>
      <%= form.date_select :data_de_nascimento, class: "form-control" %>
    </div>
    <div class="col-md-6 mb-3">
      <%= form.label :salario, class: "form-label" %>
      <%= form.number_field :salario, step: 0.01, class: "form-control", id: "salario" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mb-3">
      <%= form.label :inss, class: "form-label" %>
      <%= form.number_field :inss, step: 0.01, class: "form-control", readonly: true, id: "inss" %>
    </div>
  </div>

  <h3>Endereço</h3>
  <%= form.fields_for :endereco do |endereco_form| %>
    <div class="row">
      <div class="col-md-6 mb-3">
        <%= endereco_form.label :logradouro, class: "form-label" %>
        <%= endereco_form.text_field :logradouro, class: "form-control" %>
      </div>
      <div class="col-md-2 mb-3">
        <%= endereco_form.label :numero, class: "form-label" %>
        <%= endereco_form.text_field :numero, class: "form-control" %>
      </div>
      <div class="col-md-4 mb-3">
        <%= endereco_form.label :bairro, class: "form-label" %>
        <%= endereco_form.text_field :bairro, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 mb-3">
        <%= endereco_form.label :cidade, class: "form-label" %>
        <%= endereco_form.text_field :cidade, class: "form-control" %>
      </div>
      <div class="col-md-4 mb-3">
        <%= endereco_form.label :estado, class: "form-label" %>
        <%= endereco_form.text_field :estado, class: "form-control" %>
      </div>
      <div class="col-md-4 mb-3">
        <%= endereco_form.label :cep, class: "form-label" %>
        <%= endereco_form.text_field :cep, class: "form-control" %>
      </div>
    </div>
  <% end %>

  <h3>Telefones</h3>
  <%= form.fields_for :telefones do |telefone_form| %>
    <div class="row">
      <div class="col-md-6 mb-3">
        <%= telefone_form.label :numero, class: "form-label" %>
        <%= telefone_form.text_field :numero, class: "form-control" %>
      </div>
      <div class="col-md-6 mb-3">
        <%= telefone_form.label :tipo, class: "form-label" %>
        <%= telefone_form.select :tipo, Telefone.tipos.keys.map { |tipo| [tipo.humanize, tipo] }, {}, class: "form-control" %>
      </div>
    </div>
  <% end %>

  <div class="d-grid gap-2">
    <%= form.submit "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
    document.getElementById('salario').addEventListener('input', function() {
        const salario = this.value;
        fetch(`/proponentes/calcular_inss?salario=${salario}`)
            .then(response => response.json())
            .then(data => {
                document.getElementById('inss').value = data.inss;
            });
    });
</script>

app/views/proponentes/_proponente.html.erb
<div id="<%= dom_id(proponente) %>" class="card mb-3">
  <div class="card-header">
    <h5 class="card-title">Detalhes do Proponente</h5>
  </div>
  <div class="card-body">
    <p class="card-text">
      <strong>Nome:</strong>
      <%= proponente.nome %>
    </p>
    <p class="card-text">
      <strong>CPF:</strong>
      <%= proponente.cpf %>
    </p>
    <p class="card-text">
      <strong>Data de Nascimento:</strong>
      <%= proponente.data_de_nascimento %>
    </p>
    <p class="card-text">
      <strong>Salário:</strong>
      <%= number_to_currency(proponente.salario) %>
    </p>
    <p class="card-text">
      <strong>INSS:</strong>
      <%= number_to_currency(proponente.inss) %>
    </p>
  </div>
</div>

app/views/proponentes/edit.html.erb
<h1 class="mb-3">Editar Proponente</h1>

<%= render "form", proponente: @proponente %>

<div class="mt-4">
  <%= link_to "Visualizar", @proponente, class: "btn btn-primary" %> |
  <%= link_to "Voltar", proponentes_path, class: "btn btn-secondary" %>
</div>

app/views/proponentes/index.html.erb
<p class="text-success"><%= notice %></p>

<h1>Proponentes</h1>

<div id="proponentes" class="mt-4">
  <% @proponentes.each do |proponente| %>
    <div class="card mb-3">
      <div class="card-body">
        <%= render proponente %>
        <p>
          <%= link_to "Visualizar", proponente, class: "btn btn-info" %>
        </p>
      </div>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center mt-4">
  <%= paginate @proponentes %>
</div>

<%= link_to "Novo Proponente", new_proponente_path, class: "btn btn-primary mt-4" %>

app/views/proponentes/new.html.erb
<h1 class="mb-3">Novo Proponente</h1>

<%= render "form", proponente: @proponente %>

<div class="mt-4">
  <%= link_to "Voltar", proponentes_path, class: "btn btn-secondary" %>
</div>

app/views/proponentes/relatorio.html.erb
<h1>Relatório de Proponentes</h1>

<% @proponentes.each do |faixa, proponentes| %>
  <h2><%= faixa %></h2>
  <ul>
    <% proponentes.each do |proponente| %>
      <li><%= proponente.nome %> - <%= number_to_currency(proponente.salario) %></li>
    <% end %>
  </ul>
<% end %>

<%= line_chart @faixa_salarial, xtitle: "Faixa Salarial", ytitle: "Quantidade de Proponentes", height: "500px", library: { scales: { yAxes: [{ ticks: { beginAtZero: true } }] } } %>

app/views/proponentes/show.html.erb
<p class="text-success"><%= notice %></p>

<%= render @proponente %>

<h3 class="mt-4">Atualizar Salário</h3>
<%= form_with url: atualizar_salario_proponente_path(@proponente), method: :patch, local: true, class: "needs-validation" do %>
  <div class="form-group">
    <%= label_tag :salario, "Novo Salário" %>
    <%= number_field_tag :salario, nil, step: 0.01, class: "form-control" %>
  </div>
  <%= submit_tag "Atualizar Salário", class: "btn btn-primary" %>
<% end %>

<div class="mt-4">
  <%= link_to "Editar", edit_proponente_path(@proponente), class: "btn btn-secondary" %> |
  <%= link_to "Voltar", proponentes_path, class: "btn btn-secondary" %>

  <%= button_to "Excluir", @proponente, method: :delete, class: "btn btn-danger" %>
</div>

app/views/telefones/_form.html.erb
<%= form_with(model: telefone) do |form| %>
  <% if telefone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(telefone.errors.count, "error") %> prohibited this telefone from being saved:</h2>

      <ul>
        <% telefone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.text_field :numero %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.text_field :tipo %>
  </div>

  <div>
    <%= form.label :proponente_id, style: "display: block" %>
    <%= form.text_field :proponente_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/telefones/_telefone.html.erb
<div id="<%= dom_id telefone %>">
  <p>
    <strong>Numero:</strong>
    <%= telefone.numero %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= telefone.tipo %>
  </p>

  <p>
    <strong>Proponente:</strong>
    <%= telefone.proponente_id %>
  </p>

</div>

app/views/telefones/edit.html.erb
<h1>Editing telefone</h1>

<%= render "form", telefone: @telefone %>

<br>

<div>
  <%= link_to "Show this telefone", @telefone %> |
  <%= link_to "Back to telefones", telefones_path %>
</div>

app/views/telefones/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Telefones</h1>

<div id="telefones">
  <% @telefones.each do |telefone| %>
    <%= render telefone %>
    <p>
      <%= link_to "Show this telefone", telefone %>
    </p>
  <% end %>
</div>

<%= link_to "New telefone", new_telefone_path %>

app/views/telefones/new.html.erb
<h1>New telefone</h1>

<%= render "form", telefone: @telefone %>

<br>

<div>
  <%= link_to "Back to telefones", telefones_path %>
</div>

app/views/telefones/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @telefone %>

<div>
  <%= link_to "Edit this telefone", edit_telefone_path(@telefone) %> |
  <%= link_to "Back to telefones", telefones_path %>

  <%= button_to "Destroy this telefone", @telefone, method: :delete %>
</div>